### ISSUE TITLE
Error when deploying to Netlify

### ISSUE THREAD

**Issue by flomllr** [frangio/netlify-latex#2]
Hi,
I just tried deploying the repo to Netlify and the deploy failed with the following error:
```
install-tl-20190227/install-tl: The TeX Live versions of the local installation and the repository being accessed are not compatible:
    local: 2018
    repository: 2019
```
Any idea on how to fix that?
Thank you.

**Comment by frangio** [comment]
Thanks for reporting @flomllr. I'll look into it and get back to you.

**Comment by frangio** [comment]
Fixed in https://github.com/frangio/netlify-latex/commit/b5758c097d43d2675678d0aac84d69b14b7bf154. Thanks for reporting again!
